# Site settings
name: toplion
email: 13400717@qq.com
author: toplion
url: http://toplion.top
resume_site:
github:
baseurl: ""
description:
meta_description:
motto:
banner:

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: peiy.tian

# Build settings
markdown: kramdown

baidu_analysis:

